- name: put configuration for client lampstack in place
  template: src=files/collectd-lampstack.j2
            dest=/etc/collectd.conf
            owner=root
            group=root
            mode=0644