- name: put configuration for server collectd in place
  template: src=files/collectd-collectd.j2
            dest=/etc/collectd.conf
            owner=root
            group=root
            mode=0644