# site.yml
---
- hosts: lampstack
  sudo: true

  roles:
    - bertvv.el7
    - bertvv.httpd
    - bertvv.mariadb
    - bertvv.wordpress
    - sepolicy
    - phpmyadmin
    - { role: bertvv.collectd,
             collectd_plugins:
             [{ plugin: "cpu" },
              { plugin: "logfile"},
              { plugin: "memory" },
              { plugin: "load"}],

             collectd_plugins_multi:
             {network: { Server: '192.168.56.78' }},

            tags: ["collectd"] }

- hosts: collectd
  sudo: true
  roles:
   - bertvv.el7
   - { role: bertvv.collectd,
             collectd_plugins:
             [{ plugin: "logfile"}],

             collectd_plugins_multi:
             { rrdtool: { Datadir: '"/var/lib/collectd/rrd"' },
               network: { Listen: '192.168.56.77'}},

             tags: ["collectd"] }